---
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: test-repo-settings

  # A short description of the repository that will show up on GitHub
  description: Test repo settings.
